### ISSUE TITLE
Logging channel/sink for in-memory log failsafe

### ISSUE THREAD

**Issue by JohnathanBurchill** [CalgaryToSpace/CTS-SAT-1-OBC-Firmware#116]
(suggested by @DeflateAwning) "Add a channel which writes to an in-memory string circular buffer (maybe 4096 bytes long) which would store the most recent ~50-100 logs. Could be super helpful in case the filesystem is experiencing a failure, and the radio downlinks aren't received/logged with 100% reliability."

**Comment by DeflateAwning** [comment]
I think this was fixed in #119, and that there's nothing left to do with it. Would you mind confirming, @JohnathanBurchill? Feel free to close it if this is the case.

**Comment by JohnathanBurchill** [comment]
Fixed in #119.
