### ISSUE TITLE
ADCS Bug: Code in `main.c` was written outside of "User Code" blocks

### ISSUE THREAD

**Issue by DeflateAwning** [CalgaryToSpace/CTS-SAT-1-OBC-Firmware#190]
@DeemDeem52, the following code is being removed during an IOC file regeneration.

The following code is being removed during the regeneration (which will be merged shortly after creating this issue):

```c
  // TODO: code for testing ADCS goes here
  ADCS_initialise_crc8_checksum(); // TODO: ADCS_Init()
```

Looks like there's a few TODOs in there as well; would you mind cleaning that up in a small PR? Thanks! 

Note: This code was removed in PR #189.

**Comment by DeemDeem52** [comment]
Good catch! Thanks -- I've got a PR for this now.
