### ISSUE TITLE
Add I2C scan telecommands

### ISSUE THREAD

**Issue by DeflateAwning** [CalgaryToSpace/CTS-SAT-1-OBC-Firmware#2]
Reference the I2C scanner example in the `debug_tools/debug_i2c.c` file.

* Argument 1: Which I2C port to scan, as an integer

**Comment by robotoshi** [comment]
Create a telecommand that just scans the I2C bus to verify the devices are connected and working.

Possible starting point:
https://deepbluembedded.com/stm32-i2c-scanner-hal-code-example/

**Comment by DeflateAwning** [comment]
@parkerg-13, any luck on this one? Message me if you have any questions!

**Comment by parkerg-13** [comment]
@DeflateAwning progress has been abit delayed recently as my work has been super busy. I will try and have an update in the next few days for you.
