### ISSUE TITLE
Antenna Deploy: Create watchdog servicer task

### ISSUE THREAD

**Issue by DeflateAwning** [CalgaryToSpace/CTS-SAT-1-OBC-Firmware#203]
During parts of the mission, we will disable power to the antenna deploy mechanism. We need a global variable indicating whether the system is powered on or not.

In a thread, if the system is powered on, we must periodically service its watchdog.

**Comment by Makiv1** [comment]
I just reread the documentation for the antenna deploy system and it turns out it does not have a watchdog. Sorry about that, it seems the watchdog was one of my hallucinations.

**Comment by DeflateAwning** [comment]
Oh amazing, thanks for looking into that!
