### ISSUE TITLE
OBC Bring up Testing: Create Telecommand to Set Dipole Switch State

### ISSUE THREAD

**Issue by aaryandeshpande** [CalgaryToSpace/CTS-SAT-1-OBC-Firmware#226]
The UHF dipole switch allows the satellite to switch between what antenna is being used (out of the two options available). This is controlled by a single control signal from the STM, which is sent to pin “A”, while an inverter is used to send the inverted signal to pin “B”. Depending on the state at the A and B inputs (High/Low or Low/High), the respective antennas will be enabled (through RF1 or RF2).

A telecommand needs to be designed to test if the control signal to the switch is being sent correctly. The requirements are as follows.

- The control signal for the dipole switch comes out of the STM from pin 73 (PB12). 
- The telecommand should only take in one argument: Either 'A' or 'B'. 
- Based on the provided argument, the Telecommand should either pull PB12 to a HIGH state (if 'A') or a LOW state (if 'B'). 
- The state of this output should than be outputted through the Debug UART through a clear statement as a confirmation.
- Please name this telecommand "comms_dipole_switch_set_state"

**Comment by DeflateAwning** [comment]
Note that this issue was created in accordance with the OBC Rev. 1.3 PCB. 

The polarity in this issue contains a logic error of ANT1 vs. ANT2. See following tagged issue for follow-up bug.
