### ISSUE TITLE
Build and install libCSP (Exploratory)

### ISSUE THREAD

**Issue by NuclearTea** [CalgaryToSpace/CTS-SAT-1-OBC-Firmware#23]
Acceptance Criteria:

- Be able to build, install, and use libCSP in a repeatable fashion
- Create Document outlining steps

**Comment by JohnathanBurchill** [comment]
Is this still considered for FrontierSat?

**Comment by DeflateAwning** [comment]
The current plan is to develop the drivers without CSP, and work to get a demo of wireless transmission working without it at the moment.

Imo, this issue shouldn't be in this repo, as exploratory tasks are not closed by pull requests and do not offer a defined scope of implementation.
