### ISSUE TITLE
Fix using UART telecommands in Debug mode

### ISSUE THREAD

**Issue by DeflateAwning** [CalgaryToSpace/CTS-SAT-1-OBC-Firmware#28]
Potential solutions
1. Find another easy way to execute telecommands, other than by UART
2. Interrupt configuration maybe?
3. Maybe just reduce the baud rate to 9600, worst case.

**Comment by DeflateAwning** [comment]
@robotoshi, would you mind taking a look at investigating this a bit? Worst case, see if a lower baud rate (e.g., 9600) works.

**Comment by robotoshi** [comment]
Seems like this is only an issue if a telecommand is sent while the debugger is paused.
If that's the case, we won't fix.
If someone can replicate the bug in another situation, we will re-examine.

**Comment by DeflateAwning** [comment]
Well that was easy, nice, thanks

**Comment by robotoshi** [comment]
Change status from closed to not planned
