### ISSUE TITLE
Telecommand: Send configuration commands to MPI

### ISSUE THREAD

**Issue by DeflateAwning** [CalgaryToSpace/CTS-SAT-1-OBC-Firmware#32]
* Must send to MPI and then get the response and validate it was successful
* Should validate the configuration, in accordance with the MPI ICD
* The configuration command to be sent to the MPI should be encoded in hex

#### Potential Example Commands

```
// HV_INNER_DOME_SCAN_MODE set to sawtooth:
CTS1+mpi_send_command_hex(0204)!

// AGC_DISABLE (command 10 in decimal)
CTS1+mpi_send_command_hex(0A)

// AGC_SET_PIXEL_RANGE (command 22 = 0x16), each part set to the value "1"
CTS1+mpi_send_command_hex(1600010001)

// Could maybe support optional underscores between parts to make it more readable. Eg:
CTS1+mpi_send_command_hex(16_0001_0001)
```
Note: 'TC' (0x54 0x43) config command identifier must also be part of the configuration command being sent to the MPI followed by the command code + other args as required

**Comment by parker-research** [comment]
@vaibhavkpr, if you rebase to main, you'll be able to use the well-tested `TCMD_extract_hex_array_arg()` function now!
