### ISSUE TITLE
Integrate a SHA256 hash function

### ISSUE THREAD

**Issue by DeflateAwning** [CalgaryToSpace/CTS-SAT-1-OBC-Firmware#38]
Create a function called `GEN_sha256_hash(input_arr, input_arr_len, output_arr)`, where output_arr is 32 bytes long.

Compute the hash, using an existing implementation.

Create unit tests for short inputs, long inputs, inputs with nulls, and at least 20 random inputs generated with python (or similar).

This will be used in the telecommand uplink validation and authentication mechanism, as well as maybe others.

Benchmark the performance, and leave a comment on how long this takes to compute.

**Comment by robotoshi** [comment]
Should use this library:
https://www.st.com/en/embedded-software/x-cube-cryptolib.html

**Comment by Makiv1** [comment]
Hi, I've integrated the library on the attached branch. Should I only keep the sha256 header files or keep all of the header files for the other cryptographic functions?

**Comment by DeflateAwning** [comment]
I think that linked library is meant to be enabled via the IOC file and the CubeMX code generation. Either's fine for now!

**Comment by DeflateAwning** [comment]
Finally got the ST_Cryptolib library enabled in the `main` branch (in 603f8e01d6ef35b0b286dce3aaf80f4f5790c34c).

I believe this project is in progress in the `marko-sha256` branch. @Makiv1 can update that branch to use the new library, which will close this issue.

**Comment by DeflateAwning** [comment]
After struggling through with STMicroelectronics libraries which contain pre-compiled mystery chunks, and the SAFEA1 library, which contains paths with `#` in them (which destroy Makefiles), I recommend using a very simple C implementation, like this one: https://github.com/B-Con/crypto-algorithms.

For an example of how to use that, see: https://github.com/B-Con/crypto-algorithms/pull/9/files

I recommend applying the change in this PR here: https://github.com/B-Con/crypto-algorithms/pull/21/files

Thanks!

**Comment by robotoshi** [comment]
Another library recommendation.  It's optimized for Cortex-M

https://github.com/ctz/cifra/
