### ISSUE TITLE
LFS: Benchmark read/write performance, investigate opportunities to increase write performance

### ISSUE THREAD

**Issue by DeflateAwning** [CalgaryToSpace/CTS-SAT-1-OBC-Firmware#57]
* Setup a macro to disable debugging UART prints in the critical path of LFS writes (i.e., in the FLASH and LFS drivers/implementations).
* Create a telecommand to benchmark the read/write performance by reading and writing large files. Output a report with the speeds.
* Find ways to optimize these speeds, if required (TBC).

**Comment by parker-research** [comment]
Started a branch (`parker/lfs-benchmarking-i57`). 

On reading a 31-byte file, it takes 96ms with debugging prints enabled, and 86ms with them disabled.

After creating a flash driver benchmarking (so no LittleFS) involvement, the benchmark shows the following (127 byte test):
```
Received telecommand (len=47): 'CTS1+flash_benchmark_erase_write_read(0,0,127)!'↴
======= Telecommand ======↴
Received telecommand 'flash_benchmark_erase_write_read'↴
======== Response (duration=475ms, err=0) ========↴
Erase: 472 ms↴
Write: 2 ms↴
Read: 1 ms↴
↴
==========================↴
```

That is, the erase is the part that takes the longest (by a large margin), but the read/write also take a surprisingly-long time.

With a 512-byte test, timing was 4ms read and 4ms write. 512 bytes per 4ms is 1024 megabits per second (Mbps), which is on par with the current bus speed configuration. No problems at the flash level, thankfully.

**Comment by parker-research** [comment]
LFS benchmarking appears to show that there's a memory leak or similar, because it slows down on each subsequent benchmark execution.

The first benchmarks (fastest at the start) were `127 bytes per 50 ms` = 20 kilobits per second. More work is required.

**Comment by JohnathanBurchill** [comment]
I've played with the LFS code. 

-Mounting the filesystem takes a few seconds. 
-Listing a directory takes a few seconds, even with just a few files
-Truncating a file to 1337 bytes takes a few seconds

**Comment by DeflateAwning** [comment]
I'm kinda thinking we might need to "stream" the MPI data directly into the flash memory as raw data, and then copy it into a file (and store metadata, like timestamps/location associations) for downlink upon stopping the MPI data collection. 

This won't be an issue imo, because we have 4 memory modules. We could use one flash module as this temporary store, and the others for LittleFS, if we're still having really bad performance.

**Comment by JohnathanBurchill** [comment]
That could work very well. Let's see how it goes with profiling LFS.

**Comment by parker-research** [comment]
Timing seems quite variable, unfortunately. 

Here is the minimum timing I've seen for a small file write-then-read:

```
// 123 bytes x 1 time
======== Response (duration=92ms, err=0) ========↴
Write open: 32 ms↴
Write: 0 ms↴
Write close: 16 ms↴
Read open: 42 ms↴
Read: 0 ms↴
Read close: 0 ms↴
```

Large files (e.g., 123 bytes x 10 times = 1230 bytes) take >1 second with this flash module.

123 bytes x 1000 times (123,000 bytes) takes longer, but executes in a reasonable amount of time for the size, suggesting that LFS may be quite effective for storing larger (>100 KiB) files in a double-buffer setup (where the first stage buffer is either an array or a raw flash module with no filesystem).

```
// 123 bytes x 1000 times (123,000 bytes)
======== Response (duration=4590ms, err=0) ========↴
Write open: 126 ms↴
Write: 3164 ms↴
Write close: 27 ms↴
Read open: 134 ms↴
Read: 1138 ms↴
Read close: 0 ms↴
```

It seems that the bulk of the time may be spent in the "erase block" stage, which means that using a memory module with smaller blocks may allow it to perform better.

**Comment by JohnathanBurchill** [comment]
Possibly relevant: [LFS open issue on write performance](https://github.com/littlefs-project/littlefs/issues/535)

**Comment by JohnathanBurchill** [comment]
LFS has 480 open issues...

**Comment by JohnathanBurchill** [comment]
Your branch compiles and flashes. When running `flash_benchmark_erase_write_read(0, 0, 128)` I get this:

```
Received telecommand (len=49): 'CTS1+flash_benchmark_erase_write_read(0, 0, 128)!'
======= Telecommand ======
Received telecommand 'flash_benchmark_erase_write_read'
======== Response (duration=1ms, err=1 !!!!!! ERROR !!!!!!) ========
Error parsing arguments. Return codes: arg0=0, arg1=3, arg2=3
==========================
```

**Comment by JohnathanBurchill** [comment]
`fs_benchmark_write_read(100, 1)` gives similar error for its second argument (return value 3). If `fs_mount()` is sent first (which is reported successful), there is no confirmation of telecommand received from `fs_benchmark...`. Dev kit then does not respond to subsequent telecommands (like `hello_world()`), though the heartbeat time prints. The uart telecommand TASK seems to be stuck...

**Comment by JohnathanBurchill** [comment]
Let me know if you cannot reproduce and I'll try running the debugger.

**Comment by JohnathanBurchill** [comment]
Does enabling compiler optimization make any difference to your benchmark results?

**Comment by JohnathanBurchill** [comment]
Problem was with spaces between arguments. Is it documented that this is not allowed?

**Comment by JohnathanBurchill** [comment]
For the flash benchmark, anything larger than 512 in the third argument reports a Verify error.

**Comment by parker-research** [comment]
Sorry about that space issue; I knew it's like that, but even worse than it being documented, the example in the [Telecommand_Spec.md](https://github.com/CalgaryToSpace/CTS-SAT-1-OBC-Firmware/blob/main/docs/Telecommand_Spec.md) doc is wrong (and shows spaces). 

For ease for now, I think we'll continue saying "spaces are illegal". I'll fix that in the docs (PR #92).

May be good to document/pre-validate those limits better, good point. I found that max chunk size for the LFS benchmark was 127 bytes and the max flash size is 512 bytes.

**Comment by JohnathanBurchill** [comment]
Dev kit does not respond to telecommands after sending `fs_mount()`. Also happens in the `main` branch. Can you reproduce?

**Comment by parker-research** [comment]
Can't reproduce based on what's in `main` at `691a9c3` (i.e., works fine for me still). What happens if you press the reset button, format it, and then try to mount? Do any of the `flash_` telecommands work?
