### ISSUE TITLE
Upgrade the HAL library

### ISSUE THREAD

**Issue by robotoshi** [CalgaryToSpace/CTS-SAT-1-OBC-Firmware#91]
Issue #39 requires the newest HAL library, or at least the full one (for CRC).
Either include the HAL library as a git submodule or use CubeMX to update it.

**Comment by DeflateAwning** [comment]
Can you provide a source? We should be on the latest one. Perhaps we just need to enable the CRC hardware support in the IOC file?

Where are we using CRC32 again? Does it need to be fast? Can we just copy-paste in a simple implementation that doesn't require using specialized hardware?

**Comment by robotoshi** [comment]
My bad, it is the most recent version.  I didn't check carefully enough before.
CubeMX must not have included the CRC part of it.

Of course it's possible to use another library, but if the functionality is built in to hardware, uses the HAL, and confirmed works on this device, I don't see any reason not to use it.

**Comment by DeflateAwning** [comment]
Let's move the CRC discussion back into #39
