### ISSUE TITLE
Create on-OBC temperature sensor driver

### ISSUE THREAD

**Issue by parker-research** [CalgaryToSpace/CTS-SAT-1-OBC-Firmware#99]
The OBC has an onboard temperature sensor connected by I2C (via I2C4).

Per the OBC schematic:
```
Model Number: STDS75DS2F
Wrong Address: 0b1001_0001 = 0x91 [from Rev 1.3 schematic]
Address: 0x48
```

Datasheet: https://www.st.com/resource/en/datasheet/stds75.pdf

Create drivers, and test it in both positive and negative temperatures.

Main deliverable: a function which returns 0 on success, and which puts the temperature into a variable named `result` by a pointer argument.

**Comment by parker-research** [comment]
Hey, @parkerg-13, any luck with this? I'm hoping we can have a PR for this merged into `main` in the next 7 days, as it would be helpful for the upcoming testing opportunity.

**Comment by parkerg-13** [comment]
Hey @parker-research, I'm pretty close to being able to put a pr up. Just have to clean a couple more things up and test a couple more things. I'll try and have it up for review Saturday so there is time for feedback.
